# Generated by Django 6.0.3 on 2026-03-13 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulu', models.CharField(max_length=100)),
                ('deskrisaun', models.TextField(blank=True, null=True)),
                ('kategoria', models.CharField(choices=[('Servisu', 'Servisu'), ('Personal', 'Personal')], default='Personal', max_length=20)),
                ('prioridade', models.CharField(choices=[('Normal', 'Normal'), ('High', 'High')], default='Normal', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.timezone)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
